Header header
uint16 status_code #ステータスコード
uint16 joy_angle_main #ジョイスティック角度データ
uint16 mechanism_steering_angle_main #ステアリング角度データ
uint16 motor_applied_voltage #印加電圧データ
int16 motor_angular_velocity #モーター角速度
int16 motor_electric_current #モーター電流データ
uint32 pulsu_count_velocity #車両速度のパルスカウント
uint16 power_supply_voltage #電源電圧 12V電源測定データ
uint16 steer_limit_rate #ステア制限率
uint16 mecha_offset_adjusted_value #メカオフセット調整値
uint16 joy_fullscale_AA_value #ジョイスティックフルスケールAA値
uint16 mecha_fullscale_BB_value #メカフルスケールBB値
uint16 steer_dynamic_limit_rate #ステア動的制限率
uint16 joy_angle_sub #ジョイスティック角度サブ
uint16 mechanism_angle_sub #メカニズム角度サブ
