Header header
float64 cycle_time
int16 angle_actual
float64 angle_deg
float64 angle_deg_acc
uint16 angle_target_vlotage
int16 velocity_actual
int16 velocity_average
int16 velocity_median
int16 acceleration_actual
int16 acceleration_average
int16 acceleration_median
float64 velocity_mps
bool clutch
bool auto_mode
bool FEW #書き込み許可線ON
bool OT  #温度異常
bool COF #過電流
bool BRK #ブレーキロックセット
bool MLD #モーター線断線
bool LVT #電源電圧低下
bool CLD #クラッチ線断線
bool PLD #メカポテンション断線
bool JLD #ジョイスティック断線
uint32 read_counter
