Header header
uint16 status_code #ステータスコード
uint16 joy_angle_main #ジョイスティック角度データ
uint16 mechanism_pedal_angle_main #ペダル角度データ
uint16 motor_applied_voltage #印加電圧データ
uint16 motor_angular_velocity #モーター角速度
uint16 motor_electric_current #モーター電流データ
uint16 pulsu_count_engine #車両速度のパルスカウント
uint16 power_supply_voltage #電源電圧 12V電源測定データ
uint16 reserve1
uint16 mecha_offset_adjusted_value #メカオフセット調整値
uint16 joy_fullscale_AA_value #ジョイスティックフルスケールAA値
uint16 mecha_fullscale_BB_brake_value #メカフルスケールBB値(ブレーキ側)
uint16 mecha_fullscale_BB_accele_value #メカフルスケールBB値(アクセル側)
uint16 joy_angle_sub #ジョイスティック角度サブ
uint16 mechanism_angle_sub #メカニズム角度サブ
